
POST http://localhost:8080/barbearia
Content-Type: application/json

{
    "nome": "Cariani Barber",
    "email": "crackiani@gmail.com",
    "telefone": "11978057895",
    "cnpj": "05133159000106",
    "servicos": {
        "nome": "Corte",
	    "valor": 50
    }
}

###

POST http://localhost:8080/servicos
Content-Type: application/json

{
	"nome": "Corte",
	"valor": 50,
	"barbearia": {
		"id": 1
	}
}

###
GET http://localhost:8080/barbearia

###
GET http://localhost:8080/barbearia/nome?nome=Cariani+Barber

###
GET http://localhost:8080/barbearia/1

###

DELETE http://localhost:8080/barbearia/1

###

PUT http://localhost:8080/barbearia/1
Content-Type: application/json

{
    "nome": "Renato Cariani2",
    "email": "crackiani@gmail.com",
    "telefone": "11978057895",
    "cnpj": "30133297000124"
}

###